# Generated by Django 4.2.26 on 2025-11-24 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contracheque', 'Contracheque'), ('rescisao', 'Rescisão')], max_length=20)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
