# Generated by Django 4.2.26 on 2025-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocalculo',
            name='nome_funcionario',
            field=models.CharField(default='Não Informado', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicocalculo',
            name='resultado_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicocalculo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
